package com.linuxdroid.linux.bootstrap

import com.linuxdroid.core.logging.LinuxDroidLogger
import com.linuxdroid.core.logging.LogSubsystem
import com.linuxdroid.core.model.Architecture
import com.linuxdroid.core.model.Distribution
import com.linuxdroid.core.runtime.ElfValidator
import java.io.File
import java.nio.file.Files
import java.nio.file.Path

/**
 * Result of individual validation check.
 */
data class ValidationCheckResult(
    val name: String,
    val passed: Boolean,
    val detail: String,
)

/**
 * Comprehensive report generated by [RootfsValidator].
 */
data class RootfsValidationReport(
    val isValid: Boolean,
    val distribution: Distribution,
    val architecture: Architecture,
    val checks: List<ValidationCheckResult>,
    val errors: List<String>,
) {
    fun formatSummary(): String = buildString {
        appendLine("=== ROOTFS VALIDATION REPORT (${distribution.displayName} / ${architecture.abiName}) ===")
        appendLine("Status: ${if (isValid) "PASS" else "FAIL"}")
        checks.forEach { check ->
            appendLine(" [${if (check.passed) "✓" else "✗"}] ${check.name}: ${check.detail}")
        }
        if (errors.isNotEmpty()) {
            appendLine("Errors:")
            errors.forEach { appendLine("  - $it") }
        }
    }.trimEnd()
}

/**
 * Validates structural integrity, mandatory binaries, guest symlink chains,
 * ELF architectures, and PT_INTERP dynamic linkers for Linux root filesystems.
 */
class RootfsValidator(
    private val log: LinuxDroidLogger = LinuxDroidLogger(LogSubsystem.BOOTSTRAP),
) {

    /**
     * Resolves a guest path (e.g. `/lib/ld-linux-aarch64.so.1` or `/bin/sh`) strictly
     * within [rootfsDir], following all symlinks up to [maxHops].
     *
     * Guest absolute symlinks (e.g. `-> /usr/bin/bash`) are resolved relative to [rootfsDir],
     * NOT the Android host root `/`.
     *
     * Returns the host [File] pointing to the final target, or null if broken/escaping/circular.
     */
    fun resolveGuestSymlink(rootfsDir: File, guestPath: String, maxHops: Int = 16): File? {
        val rootfsCanonical = rootfsDir.canonicalFile
        var current = File(rootfsCanonical, guestPath.removePrefix("/"))
        var hops = 0

        while (hops < maxHops) {
            val currentPath: Path = current.toPath()
            if (!Files.isSymbolicLink(currentPath)) {
                // Not a symlink: verify existence and boundary
                if (!current.exists()) return null
                val targetCanonical = current.canonicalFile
                if (!targetCanonical.path.startsWith(rootfsCanonical.path)) {
                    log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Path traversal out of rootfs detected: ${current.path}")
                    return null
                }
                return current
            }

            // It is a symlink: read link target
            val rawTarget = try {
                Files.readSymbolicLink(currentPath).toString()
            } catch (e: Exception) {
                log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Failed to read symlink ${current.path}: ${e.message}")
                return null
            }

            hops++
            current = if (rawTarget.startsWith("/")) {
                // Absolute guest link: interpret relative to rootfsDir!
                File(rootfsCanonical, rawTarget.removePrefix("/"))
            } else {
                // Relative link: resolve relative to symlink's parent directory
                File(current.parentFile ?: rootfsCanonical, rawTarget)
            }
        }

        log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Symlink loop detected for $guestPath (exceeded $maxHops hops)")
        return null
    }

    /**
     * Executes comprehensive validation on [rootfsDir] for [distribution] and [architecture].
     */
    fun validate(
        rootfsDir: File,
        distribution: Distribution,
        architecture: Architecture = Architecture.ARM64,
        requireGraphicalStack: Boolean = false,
        username: String? = null,
    ): RootfsValidationReport {
        val checks = mutableListOf<ValidationCheckResult>()
        val errors = mutableListOf<String>()

        log.info("[BOOTSTRAP_VALIDATE] Validating rootfs at ${rootfsDir.path} for ${distribution.displayName} (${architecture.abiName})")

        // 1. Rootfs Directory Existence
        if (!rootfsDir.exists() || !rootfsDir.isDirectory) {
            val msg = "Rootfs directory does not exist or is not a directory: ${rootfsDir.path}"
            errors.add(msg)
            checks.add(ValidationCheckResult("rootfs_directory", false, msg))
            return RootfsValidationReport(false, distribution, architecture, checks, errors)
        }
        checks.add(ValidationCheckResult("rootfs_directory", true, "Directory exists at ${rootfsDir.path}"))

        // 2. Structural Linux Directories
        val requiredDirs = listOf("etc", "usr", "tmp", "dev", "proc", "sys")
        val missingDirs = requiredDirs.filter { !File(rootfsDir, it).exists() }
        if (missingDirs.isNotEmpty()) {
            val msg = "Missing essential rootfs directories: $missingDirs"
            errors.add(msg)
            checks.add(ValidationCheckResult("structural_directories", false, msg))
        } else {
            checks.add(ValidationCheckResult("structural_directories", true, "Essential directories present ($requiredDirs)"))
        }

        // 3. Mandatory Binary Checks: /bin/sh, /bin/bash, /usr/bin/bash, /usr/bin/env, /bin/true
        val requiredBinaries = listOf(
            "/bin/sh",
            "/usr/bin/env",
        )
        for (bin in requiredBinaries) {
            val resolved = resolveGuestSymlink(rootfsDir, bin)
            if (resolved == null || !resolved.exists()) {
                val msg = "Mandatory guest binary missing or broken symlink: $bin"
                errors.add(msg)
                checks.add(ValidationCheckResult("binary_$bin", false, msg))
            } else if (!resolved.canRead()) {
                val msg = "Guest binary not readable: $bin (${resolved.path})"
                errors.add(msg)
                checks.add(ValidationCheckResult("binary_$bin", false, msg))
            } else {
                checks.add(ValidationCheckResult("binary_$bin", true, "Found at ${resolved.path}"))
            }
        }

        // Check for shell (bash or sh)
        val bashResolved = resolveGuestSymlink(rootfsDir, "/bin/bash") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/bash")
        val shResolved = resolveGuestSymlink(rootfsDir, "/bin/sh") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/sh")
        if (bashResolved == null && shResolved == null) {
            val msg = "Neither /bin/bash nor /bin/sh resolved to a usable shell executable"
            errors.add(msg)
            checks.add(ValidationCheckResult("shell_executable", false, msg))
        } else {
            val activeShell = bashResolved ?: shResolved
            checks.add(ValidationCheckResult("shell_executable", true, "Resolved shell at ${activeShell?.path}"))
        }

        // 3.1 Mandatory Persistent Guest Init: /sbin/linuxdroid-init
        val guestInitFile = resolveGuestSymlink(rootfsDir, "/sbin/linuxdroid-init")
        if (guestInitFile == null || !guestInitFile.exists()) {
            val msg = "Mandatory guest init executable missing: /sbin/linuxdroid-init"
            errors.add(msg)
            checks.add(ValidationCheckResult("guest_init", false, msg))
        } else if (!guestInitFile.canRead() || !guestInitFile.canExecute()) {
            val msg = "Guest init /sbin/linuxdroid-init is not executable (canRead=${guestInitFile.canRead()}, canExecute=${guestInitFile.canExecute()})"
            errors.add(msg)
            checks.add(ValidationCheckResult("guest_init", false, msg))
        } else {
            val firstLine = try { guestInitFile.bufferedReader().readLine() } catch (_: Exception) { null }
            if (firstLine?.startsWith("#!") != true) {
                val msg = "Guest init /sbin/linuxdroid-init missing valid shebang: '$firstLine'"
                errors.add(msg)
                checks.add(ValidationCheckResult("guest_init", false, msg))
            } else {
                checks.add(ValidationCheckResult("guest_init", true, "Valid persistent guest init at ${guestInitFile.path}"))
            }
        }

        // 4. ELF & PT_INTERP Validation
        val elfBinariesToCheck = listOfNotNull(
            bashResolved ?: shResolved,
            resolveGuestSymlink(rootfsDir, "/usr/bin/env"),
            resolveGuestSymlink(rootfsDir, "/bin/true") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/true"),
        ).distinctBy { it.canonicalPath }

        for (elfFile in elfBinariesToCheck) {
            val elfInfo = ElfValidator.readElfInfo(elfFile, architecture.abiName)
            if (!elfInfo.isValid) {
                val msg = "ELF validation failed for ${elfFile.name}: ${elfInfo.detail}"
                errors.add(msg)
                checks.add(ValidationCheckResult("elf_${elfFile.name}", false, msg))
            } else {
                checks.add(ValidationCheckResult("elf_${elfFile.name}", true, elfInfo.detail))

                // If executable is dynamically linked, validate its PT_INTERP dynamic linker
                elfInfo.interpreter?.let { interpGuestPath ->
                    val interpResolved = resolveGuestSymlink(rootfsDir, interpGuestPath)
                    if (interpResolved == null || !interpResolved.exists()) {
                        val msg = "Dynamic interpreter '$interpGuestPath' for ${elfFile.name} missing in rootfs"
                        errors.add(msg)
                        checks.add(ValidationCheckResult("interp_${elfFile.name}", false, msg))
                    } else {
                        val interpElf = ElfValidator.readElfInfo(interpResolved, architecture.abiName)
                        if (!interpElf.isValid) {
                            val msg = "Dynamic interpreter '$interpGuestPath' invalid: ${interpElf.detail}"
                            errors.add(msg)
                            checks.add(ValidationCheckResult("interp_${elfFile.name}", false, msg))
                        } else {
                            checks.add(ValidationCheckResult("interp_${elfFile.name}", true, "Valid dynamic linker at ${interpResolved.path}"))
                        }
                    }
                }
            }
        }

        // 5. Package Manager Configuration
        when (distribution) {
            Distribution.DEBIAN, Distribution.UBUNTU, Distribution.KALI -> {
                val aptSourcesFile = File(rootfsDir, "etc/apt/sources.list")
                val aptSourcesDir = File(rootfsDir, "etc/apt/sources.list.d")
                val hasAptSources = (aptSourcesFile.exists() && aptSourcesFile.length() > 0) ||
                        (aptSourcesDir.isDirectory && (aptSourcesDir.listFiles()?.isNotEmpty() == true))
                if (!hasAptSources) {
                    val msg = "APT package manager configuration (etc/apt/sources.list) missing for ${distribution.displayName}"
                    errors.add(msg)
                    checks.add(ValidationCheckResult("apt_sources", false, msg))
                } else {
                    checks.add(ValidationCheckResult("apt_sources", true, "APT sources configured"))
                }
            }
            else -> {
                checks.add(ValidationCheckResult("package_manager_config", true, "Distribution $distribution checked"))
            }
        }

        // 6. Complete Graphical Stack Validation (Wayland, Weston, LDDM, LDDE)
        if (requireGraphicalStack) {
            log.info("[BOOTSTRAP_VALIDATE] Validating complete graphical stack (Wayland, Weston, LDDM, LDDE)...")

            // 6.1 Wayland runtime libraries
            val candidateLibDirs = listOf(
                File(rootfsDir, "usr/lib/aarch64-linux-gnu"),
                File(rootfsDir, "usr/lib/x86_64-linux-gnu"),
                File(rootfsDir, "usr/lib64"),
                File(rootfsDir, "usr/lib"),
                File(rootfsDir, "lib/aarch64-linux-gnu"),
                File(rootfsDir, "lib/x86_64-linux-gnu"),
                File(rootfsDir, "lib64"),
                File(rootfsDir, "lib"),
            )
            val hasWaylandClient = candidateLibDirs.any { dir ->
                File(dir, "libwayland-client.so.0").exists() || File(dir, "libwayland-client.so").exists()
            }
            val hasWaylandServer = candidateLibDirs.any { dir ->
                File(dir, "libwayland-server.so.0").exists() || File(dir, "libwayland-server.so").exists()
            }
            if (!hasWaylandClient || !hasWaylandServer) {
                val msg = "Wayland runtime libraries missing (client=$hasWaylandClient, server=$hasWaylandServer)"
                errors.add(msg)
                checks.add(ValidationCheckResult("wayland_runtime", false, msg))
            } else {
                checks.add(ValidationCheckResult("wayland_runtime", true, "libwayland-client and server libraries present"))
            }

            // 6.2 Weston compositor
            val westonResolved = resolveGuestSymlink(rootfsDir, "/usr/bin/weston") ?: resolveGuestSymlink(rootfsDir, "/usr/local/bin/weston")
            val hasHeadlessBackend = rootfsDir.walkTopDown().maxDepth(6).any { it.name == "headless-backend.so" }
            if (westonResolved == null || !westonResolved.exists()) {
                val msg = "Weston compositor executable (/usr/bin/weston) missing"
                errors.add(msg)
                checks.add(ValidationCheckResult("weston_executable", false, msg))
            } else if (!westonResolved.canExecute()) {
                val msg = "Weston compositor executable (${westonResolved.path}) not executable"
                errors.add(msg)
                checks.add(ValidationCheckResult("weston_executable", false, msg))
            } else if (!hasHeadlessBackend) {
                val msg = "Weston headless-backend.so module missing in rootfs"
                errors.add(msg)
                checks.add(ValidationCheckResult("weston_backend", false, msg))
            } else {
                checks.add(ValidationCheckResult("weston_executable", true, "Weston compositor present with headless backend"))
            }

            // 6.3 LDDM (LinuxDroid Display Manager)
            val lddmResolved = resolveGuestSymlink(rootfsDir, "/usr/bin/lddm") ?: resolveGuestSymlink(rootfsDir, "/usr/local/bin/lddm")
            val lddmConf = File(rootfsDir, "etc/linuxdroid/lddm.conf")
            val dpkgStatusText = try { File(rootfsDir, "var/lib/dpkg/status").readText() } catch (_: Exception) { "" }
            val lddmInDpkg = dpkgStatusText.contains("Package: linuxdroid-display-manager") &&
                    dpkgStatusText.contains("Status: install ok installed")

            if (lddmResolved == null || !lddmResolved.exists()) {
                val msg = "LDDM display manager executable (/usr/bin/lddm) missing"
                errors.add(msg)
                checks.add(ValidationCheckResult("lddm_executable", false, msg))
            } else if (!lddmResolved.canExecute()) {
                val msg = "LDDM executable not executable: ${lddmResolved.path}"
                errors.add(msg)
                checks.add(ValidationCheckResult("lddm_executable", false, msg))
            } else if (!lddmConf.exists()) {
                val msg = "LDDM configuration file (/etc/linuxdroid/lddm.conf) missing"
                errors.add(msg)
                checks.add(ValidationCheckResult("lddm_config", false, msg))
            } else if (!lddmInDpkg) {
                val msg = "linuxdroid-display-manager package not registered in /var/lib/dpkg/status"
                errors.add(msg)
                checks.add(ValidationCheckResult("lddm_package_state", false, msg))
            } else {
                checks.add(ValidationCheckResult("lddm_subsystem", true, "LDDM package, executable, and config verified"))
            }

            // 6.4 LDDE (LinuxDroid Desktop Environment)
            val lddeResolved = resolveGuestSymlink(rootfsDir, "/usr/bin/ldde") ?:
                    resolveGuestSymlink(rootfsDir, "/usr/bin/ldde-session") ?:
                    resolveGuestSymlink(rootfsDir, "/usr/local/bin/ldde")
            val lddeConf = File(rootfsDir, "etc/linuxdroid/desktop.conf")
            val lddeInDpkg = dpkgStatusText.contains("Package: linuxdroid-desktop-environment") &&
                    dpkgStatusText.contains("Status: install ok installed")

            if (lddeResolved == null || !lddeResolved.exists()) {
                val msg = "LDDE desktop executable (/usr/bin/ldde) missing"
                errors.add(msg)
                checks.add(ValidationCheckResult("ldde_executable", false, msg))
            } else if (!lddeResolved.canExecute()) {
                val msg = "LDDE executable not executable: ${lddeResolved.path}"
                errors.add(msg)
                checks.add(ValidationCheckResult("ldde_executable", false, msg))
            } else if (!lddeConf.exists()) {
                val msg = "LDDE configuration file (/etc/linuxdroid/desktop.conf) missing"
                errors.add(msg)
                checks.add(ValidationCheckResult("ldde_config", false, msg))
            } else if (!lddeInDpkg) {
                val msg = "linuxdroid-desktop-environment package not registered in /var/lib/dpkg/status"
                errors.add(msg)
                checks.add(ValidationCheckResult("ldde_package_state", false, msg))
            } else {
                checks.add(ValidationCheckResult("ldde_subsystem", true, "LDDE package, executable, and config verified"))
            }
        }

        // 7. User Account Validation (if specified)
        if (username != null && username.isNotBlank()) {
            val passwdFile = File(rootfsDir, "etc/passwd")
            val homeDirectory = File(rootfsDir, "home/$username")
            val sudoersFile = File(rootfsDir, "etc/sudoers.d/01linuxdroid-$username")

            val userInPasswd = passwdFile.exists() && passwdFile.readLines().any { it.startsWith("$username:") }
            if (!userInPasswd) {
                val msg = "Configured user '$username' not found in /etc/passwd"
                errors.add(msg)
                checks.add(ValidationCheckResult("user_account", false, msg))
            } else {
                checks.add(ValidationCheckResult("user_account", true, "User '$username' registered in /etc/passwd"))
            }

            if (!homeDirectory.exists()) {
                val msg = "User home directory missing: /home/$username"
                errors.add(msg)
                checks.add(ValidationCheckResult("user_home", false, msg))
            } else {
                checks.add(ValidationCheckResult("user_home", true, "Home directory present at /home/$username"))
            }

            if (!sudoersFile.exists()) {
                val msg = "Sudo configuration missing: /etc/sudoers.d/01linuxdroid-$username"
                errors.add(msg)
                checks.add(ValidationCheckResult("user_sudo", false, msg))
            } else {
                checks.add(ValidationCheckResult("user_sudo", true, "Sudo access configured for '$username'"))
            }
        }

        val isValid = errors.isEmpty()
        if (isValid) {
            log.info("[BOOTSTRAP_VALIDATE] Rootfs validation PASSED for ${distribution.displayName} (graphicalStack=$requireGraphicalStack)")
        } else {
            log.warn("[BOOTSTRAP_VALIDATE] Rootfs validation FAILED for ${distribution.displayName} (graphicalStack=$requireGraphicalStack): $errors")
        }

        return RootfsValidationReport(
            isValid = isValid,
            distribution = distribution,
            architecture = architecture,
            checks = checks,
            errors = errors,
        )
    }

    /**
     * Stage A — Extraction Validation:
     * Validates structural filesystem integrity immediately after rootfs archive extraction.
     * Does NOT require graphical packages or runtime services.
     */
    fun validateExtraction(
        rootfsDir: File,
        distribution: Distribution,
        architecture: Architecture = Architecture.ARM64,
    ): RootfsValidationReport {
        log.info("[STAGE_A] Executing Extraction Validation for ${distribution.displayName}")
        return validate(
            rootfsDir = rootfsDir,
            distribution = distribution,
            architecture = architecture,
            requireGraphicalStack = false,
            username = null,
        )
    }

    /**
     * Stage B — Runtime Validation:
     * Validates persistent guest init and runtime infrastructure files.
     */
    fun validateRuntime(rootfsDir: File): Boolean {
        log.info("[STAGE_B] Executing Runtime Infrastructure Validation")
        val guestInit = resolveGuestSymlink(rootfsDir, "/sbin/linuxdroid-init")
        val initValid = guestInit != null && guestInit.exists() && guestInit.canExecute()
        val tmpValid = File(rootfsDir, "tmp").exists()
        val runValid = File(rootfsDir, "run").exists()
        return initValid && tmpValid && runValid
    }

    /**
     * Stage C — Graphics Deployment Validation:
     * Validates that Wayland runtime libraries, Weston compositor executable and backend,
     * LDDM, and LDDE files exist on disk.
     * Does NOT require Weston, LDDM, or LDDE processes to be actively running.
     */
    fun validateGraphics(
        rootfsDir: File,
        distribution: Distribution,
        architecture: Architecture = Architecture.ARM64,
    ): RootfsValidationReport {
        log.info("[STAGE_C] Executing Graphics Deployment Validation (files only, no live GUI required)")
        return validate(
            rootfsDir = rootfsDir,
            distribution = distribution,
            architecture = architecture,
            requireGraphicalStack = true,
            username = null,
        )
    }

    /**
     * Stage D — Final Rootfs Validation:
     * Comprehensive validation of complete installed baseline, user account, shell, sudo, and APT/dpkg integrity.
     */
    fun validateFinal(
        rootfsDir: File,
        distribution: Distribution,
        architecture: Architecture = Architecture.ARM64,
        username: String? = null,
        requireGraphicalStack: Boolean = false,
    ): RootfsValidationReport {
        log.info("[STAGE_D] Executing Final Rootfs Validation (user=$username, graphicalStack=$requireGraphicalStack)")
        return validate(
            rootfsDir = rootfsDir,
            distribution = distribution,
            architecture = architecture,
            requireGraphicalStack = requireGraphicalStack,
            username = username,
        )
    }
}

